name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: "25"
          cache: sbt

      - name: Check Scala formatting
        run: sbt -v scalafmtSbtCheck scalafmtCheckAll

  test:
    name: Compile and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: "25"
          cache: sbt

      - name: Compile and test all projects
        run: sbt -v core/test numberGuesser/test ticTacToe/test launcher/test root/test
